name: Running Jest Suite
on: push
jobs:
  jest:
    name: Jest Testing
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 14.15.5
    - name: Install Node dependencies
      run: npm ci
    - name: Run Jest tests
      run: npm run jest
