name: Publish package to GitHub Packages
on:
  push:
    branches:
      - main
jobs:
  publish-package:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v2
      - run: sh ./.github/workflows/sh-scripts/install.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm publish --access public
      - run: rm .npmrc
